// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnHPLu4zvDhkI0Jz0Bcng5m8oMCWD5_KM',
    appId: '1:509613163524:web:7923415ef73a378c5ba151',
    messagingSenderId: '509613163524',
    projectId: 'flutter-dev-new',
    authDomain: 'flutter-dev-new.firebaseapp.com',
    storageBucket: 'flutter-dev-new.firebasestorage.app',
    measurementId: 'G-ZPVZLZYPPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4rC2_V2kjably0yTOlmaomUTwbOp9hhE',
    appId: '1:509613163524:android:e54ba975ffd0fc2f5ba151',
    messagingSenderId: '509613163524',
    projectId: 'flutter-dev-new',
    storageBucket: 'flutter-dev-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWoEAb-2rJ_uqidphSQzFLsvzldhNg8uY',
    appId: '1:509613163524:ios:af080f407051ee9c5ba151',
    messagingSenderId: '509613163524',
    projectId: 'flutter-dev-new',
    storageBucket: 'flutter-dev-new.firebasestorage.app',
    iosBundleId: 'com.example.tugas12Firebase',
  );
}
